###
POST http://127.0.0.1:8082/users/
Content-Type: application/json

{
    "name": "Carine Casagrande",
    "email": "carine.casagrande@hotmail.com",
    "password": "123456"
}

###
GET http://127.0.0.1:8082/users/

###
GET http://127.0.0.1:8082/users/1









###
PUT http://127.0.0.1:8082/users/1
Content-Type: application/json

{
    "name": "Carine Casa Grande",
    "email": "carinecasagrandee@edu.unifil.br",
    "birth_date": "2000-09-23T00:00:00.000Z"
}









###
POST http://127.0.0.1:8000/users
Content-Type: application/json

{
    "name": "Ricardo Silva",
    "email": "ricardo.silva@email.com"
}








###
PUT http://127.0.0.1:8000/users/8
Content-Type: application/json

{
    "name": "Nome",
    "price": 1
}

### 
DELETE http://127.0.0.1:8000/users/8
